const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],body=document.body;
const welcome=$('#welcome'),presence=$('#presence-card'),dock=$('#control-dock'),soundToggle=$('#sound-toggle'),soundLabel=soundToggle.querySelector('.button-label'),soundStatus=$('#sound-status'),soundscapeName=$('#soundscape-name'),brightness=$('#brightness'),motion=$('#motion'),volume=$('#volume'),brightnessValue=$('#brightness-value'),motionValue=$('#motion-value'),soundValue=$('#sound-value'),presenceLabel=$('#presence-label'),presenceTitle=$('#presence-title'),presenceCopy=$('#presence-copy');
const atmospheres={
 forest:{name:'Forest',base:98,fifth:147,filter:760,color:[188,234,211],motion:'float',texture:.22},ether:{name:'Ether',base:132,fifth:198,filter:1550,color:[216,198,255],motion:'orbit',texture:.12},water:{name:'Water',base:110,fifth:165,filter:1050,color:[171,235,233],motion:'ripple',texture:.25},night:{name:'Night',base:82.4,fifth:123.6,filter:520,color:[198,216,255],motion:'stars',texture:.14},dawn:{name:'Dawn',base:123.5,fifth:185.2,filter:1200,color:[255,221,178],motion:'rise',texture:.13},rain:{name:'Rain',base:92.5,fifth:138.7,filter:1900,color:[179,216,225],motion:'rain',texture:.5},firelight:{name:'Firelight',base:104,fifth:156,filter:900,color:[255,192,139],motion:'embers',texture:.2},flow:{name:'Flow',base:116.5,fifth:174.7,filter:1150,color:[177,231,217],motion:'stream',texture:.2},earth:{name:'Earth',base:73.4,fifth:110,filter:620,color:[218,191,137],motion:'dust',texture:.24},air:{name:'Air',base:147,fifth:220.5,filter:2150,color:[214,239,240],motion:'drift',texture:.1},wind:{name:'Wind',base:117,fifth:175.5,filter:1750,color:[197,230,216],motion:'wind',texture:.38}
};
const states={
 stillness:{name:'Stillness',title:'Nothing needs your attention here.',copy:'Stay for a moment. Let the screen be quiet with you.',motion:34,pitch:1,filter:.72,bells:.35,texture:.75,tempo:1.35},
 groundedness:{name:'Groundedness',title:'Come back to what is underneath you.',copy:'Less reaching. More weight. More here.',motion:28,pitch:.75,filter:.58,bells:.18,texture:1.05,tempo:1.6},
 breath:{name:'Breath',title:'Let one rhythm be enough.',copy:'Follow the field as it expands and returns.',motion:38,pitch:1,filter:.9,bells:.45,texture:.7,tempo:1},
 drift:{name:'Drift',title:'You can loosen your grip for a while.',copy:'No destination. No next thing. Just movement without demand.',motion:54,pitch:1.125,filter:1.15,bells:.6,texture:.6,tempo:.78},
 focus:{name:'Focus',title:'One thing can be enough.',copy:'The space quiets around a single center.',motion:20,pitch:1.5,filter:.68,bells:.15,texture:.35,tempo:1.8},
 samadhi:{name:'Samadhi',title:'Rest attention inside itself.',copy:'A contemplative space for sustained stillness and undivided attention.',motion:14,pitch:.5,filter:.42,bells:.08,texture:.38,tempo:2.2},
 enlightenment:{name:'Enlightenment',title:'Let the space become luminous.',copy:'An atmosphere for clarity, openness, wonder, and seeing differently.',motion:42,pitch:2,filter:1.45,bells:.82,texture:.38,tempo:.68},
 softness:{name:'Softness',title:'Nothing here needs to be hard.',copy:'Edges soften. Contrast lowers. The space holds less urgency.',motion:24,pitch:.875,filter:.72,bells:.28,texture:.55,tempo:1.4},
 release:{name:'Release',title:'You may put something down.',copy:'Let motion pass through without having to follow it.',motion:48,pitch:1.25,filter:1.08,bells:.55,texture:.8,tempo:.86},
 presence:{name:'Presence',title:'This moment does not need improvement.',copy:'Stay with what is here before adding anything else.',motion:18,pitch:1,filter:.62,bells:.12,texture:.45,tempo:1.9},
 wonder:{name:'Wonder',title:'There is still mystery here.',copy:'A little strangeness. A little beauty. No explanation required.',motion:58,pitch:1.667,filter:1.3,bells:.9,texture:.5,tempo:.62},
 rest:{name:'Rest',title:'You are allowed to stop consuming.',copy:'The quietest version of the space. Almost nothing asks anything of you.',motion:8,pitch:.5,filter:.3,bells:.02,texture:.2,tempo:3}
};
const defaults={atmosphere:'forest',state:'stillness',theme:'night',brightness:82,motion:44,volume:28,field:'center'};
let currentAtmosphere=localStorage.getItem('alive-space-atmosphere')||defaults.atmosphere,currentState=localStorage.getItem('alive-space-state')||defaults.state,currentTheme=localStorage.getItem('alive-space-theme')||defaults.theme,currentField=localStorage.getItem('alive-space-field')||defaults.field,audio=null,audioOn=false;
function soundName(){return `${atmospheres[currentAtmosphere].name} · ${states[currentState].name}`}
function enterSpace(){welcome.classList.add('hidden');setTimeout(()=>presence.classList.remove('hidden'),180)}
function openDock(){dock.classList.add('open');dock.setAttribute('aria-hidden','false');$('#controls-toggle').setAttribute('aria-expanded','true')}
function closeDock(){dock.classList.remove('open');dock.setAttribute('aria-hidden','true');$('#controls-toggle').setAttribute('aria-expanded','false')}
function updatePresence(){const a=atmospheres[currentAtmosphere],s=states[currentState];presenceLabel.textContent=`${a.name} · ${s.name}`;presenceTitle.textContent=s.title;presenceCopy.textContent=s.copy;soundscapeName.textContent=soundName()}
function setAtmosphere(v){currentAtmosphere=v;body.dataset.atmosphere=v;localStorage.setItem('alive-space-atmosphere',v);$$('[data-atmosphere]').forEach(b=>b.classList.toggle('active',b.dataset.atmosphere===v));reseedScene();updatePresence();if(audioOn)rebuildAudio()}
function setState(v,applyMotion=true){currentState=v;body.dataset.state=v;localStorage.setItem('alive-space-state',v);$$('[data-state]').forEach(b=>b.classList.toggle('active',b.dataset.state===v));if(applyMotion){motion.value=states[v].motion;setMotion(states[v].motion)}updatePresence();if(audioOn)rebuildAudio()}
function setBrightness(v){const n=+v;brightnessValue.textContent=`${n}%`;const alpha=n<100?Math.min((100-n)/100,.58):0;$('#brightness-overlay').style.background=n<100?`rgba(0,0,0,${alpha})`:`rgba(255,246,225,${Math.min((n-100)/100,.08)})`;localStorage.setItem('alive-space-brightness',n)}
function setMotion(v){const n=+v,f=n===0?.01:Math.max(.08,n/38);body.style.setProperty('--motion',f.toFixed(2));motionValue.textContent=n===0?'still':n<18?'very slow':n<38?'gentle':n<65?'alive':'immersive';localStorage.setItem('alive-space-motion',n)}
function setVolume(v){const n=+v;soundValue.textContent=n===0?'silent':n<25?'soft':n<60?'low':'present';if(audio?.master)audio.master.gain.setTargetAtTime((n/100)*.2,audio.ctx.currentTime,.15);localStorage.setItem('alive-space-volume',n)}
function setTheme(v){currentTheme=v;body.dataset.theme=v;localStorage.setItem('alive-space-theme',v);$$('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===v));document.querySelector('meta[name="theme-color"]').setAttribute('content',v==='day'?'#dfe9e3':'#07110d')}
function setFieldMode(v){currentField=v;body.dataset.fieldMode=v;localStorage.setItem('alive-space-field',v);$$('[data-field-choice]').forEach(b=>b.classList.toggle('active',b.dataset.fieldChoice===v))}
function applyFeeling(f){const map={bright:['night','softness',52,18],loud:['forest','rest',68,10],fast:['water','stillness',72,20],head:['ether','presence',66,18],restless:['earth','groundedness',76,32],quiet:['forest','rest',64,8]},p=map[f]||map.quiet;setAtmosphere(p[0]);setState(p[1],false);brightness.value=p[2];motion.value=p[3];setBrightness(p[2]);setMotion(p[3]);enterSpace()}
$$('[data-feeling]').forEach(b=>b.onclick=()=>applyFeeling(b.dataset.feeling));$('#skip-button').onclick=enterSpace;$('#choose-button').onclick=openDock;$('#controls-toggle').onclick=()=>dock.classList.contains('open')?closeDock():openDock();$('#controls-close').onclick=closeDock;$$('[data-atmosphere]').forEach(b=>b.onclick=()=>setAtmosphere(b.dataset.atmosphere));$$('[data-state]').forEach(b=>b.onclick=()=>setState(b.dataset.state));$$('[data-theme-choice]').forEach(b=>b.onclick=()=>setTheme(b.dataset.themeChoice));$$('[data-field-choice]').forEach(b=>b.onclick=()=>setFieldMode(b.dataset.fieldChoice));brightness.oninput=e=>setBrightness(e.target.value);motion.oninput=e=>setMotion(e.target.value);volume.oninput=e=>setVolume(e.target.value);
$('#reduce-button').onclick=()=>{const active=body.classList.toggle('quieter');$('#reduce-button').textContent=active?'Restore detail':'Make it quieter';if(active){motion.value=8;setMotion(8)}};$('#breath-button').onclick=()=>{const active=body.classList.toggle('breathing');$('#breath-button').textContent=active?'breathing with the field':'breathe with the field'};$('#reset-button').onclick=()=>{setAtmosphere(defaults.atmosphere);setState(defaults.state,false);setTheme(defaults.theme);setFieldMode(defaults.field);brightness.value=defaults.brightness;motion.value=defaults.motion;volume.value=defaults.volume;setBrightness(defaults.brightness);setMotion(defaults.motion);setVolume(defaults.volume);body.classList.remove('quieter','breathing')};
function noiseBuffer(ctx){const b=ctx.createBuffer(1,ctx.sampleRate*4,ctx.sampleRate),d=b.getChannelData(0);let last=0;for(let i=0;i<d.length;i++){last=(last+.02*(Math.random()*2-1))/1.02;d[i]=last*3.3}return b}
function tone(ctx,dest,freq,type='sine',gain=.02,detune=0){const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=freq;o.detune.value=detune;g.gain.value=gain;o.connect(g);g.connect(dest);o.start();return{o,g}}
function bell(ctx,dest,freq,delay,gain){const now=ctx.currentTime+delay,o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(gain,now+.03);g.gain.exponentialRampToValueAtTime(.0001,now+4);o.connect(g);g.connect(dest);o.start(now);o.stop(now+4.2)}
function scheduleBells(pack){if(!audioOn||audio!==pack)return;const a=atmospheres[currentAtmosphere],s=states[currentState],notes=[a.base*s.pitch*2,a.fifth*s.pitch*1.5,a.base*s.pitch*2.5,a.fifth*s.pitch*2];if(Math.random()<s.bells)bell(pack.ctx,pack.fx,notes[Math.floor(Math.random()*notes.length)],.05,.025+.03*s.bells);pack.timer=setTimeout(()=>scheduleBells(pack),(4500+Math.random()*6000)*s.tempo)}
function buildAudio(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;const a=atmospheres[currentAtmosphere],s=states[currentState],ctx=new AC(),master=ctx.createGain(),comp=ctx.createDynamicsCompressor(),fx=ctx.createGain();master.gain.value=(+volume.value/100)*.2;fx.connect(comp);comp.connect(master);master.connect(ctx.destination);const noise=ctx.createBufferSource();noise.buffer=noiseBuffer(ctx);noise.loop=true;const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=Math.max(180,a.filter*s.filter);const ng=ctx.createGain();ng.gain.value=a.texture*s.texture;noise.connect(filter);filter.connect(ng);ng.connect(fx);noise.start();const root=a.base*s.pitch;tone(ctx,fx,root,'sine',.026);tone(ctx,fx,a.fifth*s.pitch,'sine',.014,3);tone(ctx,fx,root/2,'triangle',.008,-4);if(['ether','enlightenment','wonder'].includes(currentAtmosphere)||['enlightenment','wonder'].includes(currentState))tone(ctx,fx,root*2.01,'sine',.006,7);const pack={ctx,master,fx,timer:null};setTimeout(()=>scheduleBells(pack),1200);return pack}
function stopAudio(){if(!audio)return;if(audio.timer)clearTimeout(audio.timer);try{audio.ctx.close()}catch{}audio=null}
function rebuildAudio(){stopAudio();audio=buildAudio();soundscapeName.textContent=soundName()}
async function toggleSound(){audioOn=!audioOn;soundToggle.setAttribute('aria-pressed',audioOn);soundLabel.textContent=audioOn?'sound on':'sound off';soundStatus.textContent=audioOn?'playing':'silent';if(audioOn){audio=buildAudio();if(audio?.ctx.state==='suspended')await audio.ctx.resume()}else stopAudio()}
soundToggle.onclick=toggleSound;
const canvas=$('#ambient-canvas'),ctx=canvas.getContext('2d');let W=0,H=0,DPR=1,particles=[];
function seed(mode){const p={x:Math.random()*W,y:Math.random()*H,a:.06+Math.random()*.18,s:.5+Math.random()*2,life:Math.random()*1000};if(mode==='rain')return{...p,vx:-.2,vy:1.8+Math.random()*2.4,len:10+Math.random()*28};if(mode==='embers')return{...p,vx:(Math.random()-.5)*.22,vy:-.3-Math.random()*.7};if(mode==='stars')return{...p,vx:0,vy:0};if(mode==='ripple')return{...p,r:2+Math.random()*24,vr:.08+Math.random()*.16};if(mode==='wind')return{...p,vx:.7+Math.random()*1.1,vy:(Math.random()-.5)*.14,len:28+Math.random()*54};if(mode==='orbit')return{...p,angle:Math.random()*Math.PI*2,rad:80+Math.random()*Math.min(W,H)*.3};return{...p,vx:(Math.random()-.5)*.08,vy:-.02-Math.random()*.09}}
function reseedScene(){const mode=atmospheres[currentAtmosphere].motion,count=Math.max(38,Math.min(88,Math.round(W/18)));particles=Array.from({length:count},()=>seed(mode))}
function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(devicePixelRatio||1,2);canvas.width=W*DPR;canvas.height=H*DPR;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0);reseedScene()}
function rgba(a){const c=atmospheres[currentAtmosphere].color;return`rgba(${c[0]},${c[1]},${c[2]},${a})`}
function draw(){ctx.clearRect(0,0,W,H);const a=atmospheres[currentAtmosphere],mode=a.motion,m=+getComputedStyle(body).getPropertyValue('--motion')||.2,cx=W*.5,cy=H*.38;particles.forEach(p=>{p.life+=m;if(mode==='orbit'){p.angle+=.0018*m;p.x=cx+Math.cos(p.angle)*p.rad;p.y=cy+Math.sin(p.angle)*p.rad}else if(mode==='ripple'){p.r+=p.vr*m*4;if(p.r>70){p.r=2;p.x=Math.random()*W;p.y=H*(.35+Math.random()*.5)}ctx.strokeStyle=rgba(Math.max(.02,p.a*(1-p.r/75)));ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.stroke();return}else{p.x+=(p.vx||0)*m;p.y+=(p.vy||0)*m}if(p.y<-40)p.y=H+20;if(p.y>H+40)p.y=-20;if(p.x<-80)p.x=W+40;if(p.x>W+80)p.x=-40;ctx.strokeStyle=ctx.fillStyle=rgba(p.a);if(mode==='rain'||mode==='wind'){ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x-(p.len||20),p.y+(mode==='rain'?(p.len||20):0));ctx.stroke()}else{ctx.beginPath();ctx.arc(p.x,p.y,p.s||1,0,Math.PI*2);ctx.fill()}});requestAnimationFrame(draw)}
addEventListener('resize',resize);resize();draw();
body.dataset.atmosphere=currentAtmosphere;body.dataset.state=currentState;setTheme(currentTheme);setFieldMode(currentField);$$('[data-atmosphere]').forEach(b=>b.classList.toggle('active',b.dataset.atmosphere===currentAtmosphere));$$('[data-state]').forEach(b=>b.classList.toggle('active',b.dataset.state===currentState));brightness.value=localStorage.getItem('alive-space-brightness')||defaults.brightness;motion.value=localStorage.getItem('alive-space-motion')||defaults.motion;volume.value=localStorage.getItem('alive-space-volume')||defaults.volume;setBrightness(brightness.value);setMotion(motion.value);setVolume(volume.value);updatePresence();
